language: generic
deploy:
  - provider: npm
    email: $EMAIL
    api_key: $API_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: ./build/app
    keep_history: true
    skip_cleanup: true
    on:
      branch: master
before_deploy:
  - npm i